version: '3'
services:
  fastapi:
    build:
      context: ./src
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:80"
    command: "uvicorn main:app --host 0.0.0.0 --port 80 --reload"

  react:
    build:
      context: ./showcase
      dockerfile: Dockerfile.react
    ports:
      - "3000:3000"
